#!/bin/sh
set -e

dir="$(cd "$(dirname "$0")" && pwd)"
src="$dir/programs/forth.sets"
bin="$dir/programs/forth.bin"
fth="$dir/programs/mandelbrot.fth"

if [ ! -f "$bin" ] || [ "$src" -nt "$bin" ]; then
  echo "compiling forth.sets..."
  cd "$dir/compiler"
  scryer-prolog -f -g "use_module(compiler), compile_file('$src', '$bin'), halt." < /dev/null
  cd "$dir"
  echo "compiled forth.sets"
fi

echo "loading..."

{ cat "$fth"; cat /dev/tty; } | "$dir/vm" "$@" "$bin"
